version: '3.8'
name: medapper-demo

services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - 6032:5432
    volumes:
      - pg-data:/var/lib/postgres/data

volumes:
  pg-data:
    driver: local